{
  "formatVersion": "1.1",
  "component": {
    "group": "org.maplibre.gl",
    "module": "android-sdk",
    "version": "10.3.1-modify",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.maplibre.gl",
          "module": "android-sdk-geojson",
          "version": {
            "requires": "5.9.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-gestures",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-10.3.1-modify.aar",
          "url": "android-sdk-10.3.1-modify.aar",
          "size": 13538750,
          "sha512": "4512ffee427e0afaf4a770fa0795bd5ea3f51a312853ce04234a3a8157b8191df6104ebfd061bd36d36abd8e1b1fb5eb99bceac1d8e9e694dfaf644456714b75",
          "sha256": "eae9e87fc00372cb117156e4b2425ae44b6f47379647e40b17e2faae8284e57d",
          "sha1": "108b333295db71d28a69dbdfcd68b86af839203e",
          "md5": "e2a57b51af358a490243548c0ffeef92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.maplibre.gl",
          "module": "android-sdk-geojson",
          "version": {
            "requires": "5.9.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-gestures",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-sdk-turf",
          "version": {
            "requires": "5.9.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-sdk-10.3.1-modify.aar",
          "url": "android-sdk-10.3.1-modify.aar",
          "size": 13538750,
          "sha512": "4512ffee427e0afaf4a770fa0795bd5ea3f51a312853ce04234a3a8157b8191df6104ebfd061bd36d36abd8e1b1fb5eb99bceac1d8e9e694dfaf644456714b75",
          "sha256": "eae9e87fc00372cb117156e4b2425ae44b6f47379647e40b17e2faae8284e57d",
          "sha1": "108b333295db71d28a69dbdfcd68b86af839203e",
          "md5": "e2a57b51af358a490243548c0ffeef92"
        }
      ]
    }
  ]
}
